{{- if .Values.maildev.config.web.authRequired }}
{{- if (not .Values.maildev.config.web.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maildev.web.secretName" . }}
data:
  web-password: {{ .Values.maildev.config.web.password | b64enc }}
{{- end }}
{{- end }}
