{{- if and .Values.maildev.persistence.enabled .Values.maildev.persistence.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.maildev.persistence.cron.config.schedule }}
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - {{ .Release.Name }}
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: delete-email-files
              image: "{{ .Values.maildev.persistence.cron.image.registry }}/{{ .Values.maildev.persistence.cron.image.repository }}:{{ .Values.maildev.persistence.cron.image.tag }}"
              imagePullPolicy: {{ .Values.maildev.persistence.cron.image.pullPolicy }}
              args:
                - "find"
                - "{{ .Values.maildev.config.mailDirectory }}"
                - "-type"
                - "f"
                - "-mmin"
                - "+{{ .Values.maildev.persistence.cron.config.minutesToKeep }}"
                - "-exec"
                - "rm"
                - "-rf"
                - "{}"
                - ";"
              volumeMounts:
                - name: data
                  mountPath: {{ .Values.maildev.config.mailDirectory | quote }}
            - name: delete-email-folders
              image: "{{ .Values.maildev.persistence.cron.image.registry }}/{{ .Values.maildev.persistence.cron.image.repository }}:{{ .Values.maildev.persistence.cron.image.tag }}"
              imagePullPolicy: {{ .Values.maildev.persistence.cron.image.pullPolicy }}
              args:
                - "find"
                - "{{ .Values.maildev.config.mailDirectory }}"
                - "-type"
                - "d"
                - "-mmin"
                - "+{{ .Values.maildev.persistence.cron.config.minutesToKeep }}"
                - "-mindepth"
                - "1"
                - "-exec"
                - "rm"
                - "-rf"
                - "{}"
                - ";"
              volumeMounts:
                - name: data
                  mountPath: {{ .Values.maildev.config.mailDirectory | quote }}
            - name: reload-mail
              image: "{{ .Values.maildev.persistence.cron.image.registry }}/{{ .Values.maildev.persistence.cron.image.repository }}:{{ .Values.maildev.persistence.cron.image.tag }}"
              imagePullPolicy: {{ .Values.maildev.persistence.cron.image.pullPolicy }}
              args: ["wget","http://{{ include "maildev.fullname" . }}-web:{{ .Values.services.web.port}}/reloadMailsFromDirectory"]
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "maildev.pvcName" . | quote }}
          restartPolicy: OnFailure
  {{- end }}
