apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.web.serviceName" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.web.type }}
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
