{{- if .Values.maildev.config.oauth2_proxy.enabled }}
{{- if (not .Values.maildev.config.oauth2_proxy.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maildev.oauth2_proxy.secretName" . }}
data:
  oauth2_proxy_client_id: {{ .Values.maildev.config.oauth2_proxy.clientId | b64enc }}
  oauth2_proxy_client_secret: {{ .Values.maildev.config.oauth2_proxy.clientSecret | b64enc }}
  oauth2_proxy_cookie_secret: {{ .Values.maildev.config.oauth2_proxy.cookieSecret | b64enc }}
  oauth2_proxy_oidc_issuer_url: {{ .Values.maildev.config.oauth2_proxy.oidcIssuerURL | b64enc }}
{{- end }}
{{- end }}
