apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.smtp.serviceName" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
  {{- if .Values.services.smtp.annotations }}
  annotations:
    {{- toYaml .Values.services.smtp.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.smtp.type }}
  ports:
    - port: {{ .Values.services.smtp.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
      {{- if and (eq .Values.services.smtp.type "NodePort") .Values.services.smtp.nodePort }}
      nodePort: {{ .Values.services.smtp.nodePort }}
      {{- end }}
  {{- if and (eq .Values.services.smtp.type "LoadBalancer") .Values.services.smtp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.services.smtp.loadBalancerIP | quote }}
  {{- end }}
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
