apiVersion: v2
name: maildev
description: MailDev is a simple way to test your emails during development with an easy to use web interface.
type: application
version: 1.1.1
appVersion: "2.1.0"
home: https://github.com/alluen/maildev-helm
maintainers:
  - name: chent1
    email: chent1@ohio.edu
sources:
  - https://maildev.github.io/maildev
  - https://github.com/maildev/maildev
  - https://hub.docker.com/r/maildev/maildev
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: image version to 2.1.0
  artifacthub.io/screenshots: |
    - title: SMTP server & web interface for viewing and testing emails during development.
      url: https://maildev.github.io/maildev/assets/img/original/maildev-light.png
    - title: Resizable viewport to test your emails at different sizes.
      url: https://maildev.github.io/maildev/assets/img/original/responsive.png
    - title: View email HTML, plain text, headers or raw source.
      url: https://maildev.github.io/maildev/assets/img/original/formats.png
    - title: Convenient search feature to quickly find any email.
      url: https://maildev.github.io/maildev/assets/img/original/search.png
    - title: View your emails in an eye-friendly dark interface.
      url: https://maildev.github.io/maildev/assets/img/original/maildev-dark.png
